# Generated by Django 5.1.4 on 2024-12-18 20:49
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("library_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcategory",
            options={"verbose_name_plural": "Book categories"},
        ),
        migrations.AlterField(
            model_name="author",
            name="year_of_birth_date",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
