# Generated by Django 5.1.4 on 2024-12-20 16:23
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("library_api", "0003_alter_bookcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(fields=("first_name", "last_name"), name="unique_full_name"),
        ),
    ]
