repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.10
        args: [--line-length=120]
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [
            --application-directories, '.:src',
            --py38-plus,
            --add-import, 'from __future__ import annotations',
        ]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    name: bandit
    entry: bandit
    args: ["-r", ".", "--exclude", "./venv/,./tests/*test*.py"]
    language: python
    types: [python]
    pass_filenames: false
    always_run: true
- repo: local
  hooks:
    - id: mypy
      name: mypy (local)
      entry: mypy
      language: system
      types: [python]
      args: ["--config-file=mypy.ini", "--explicit-package-bases", "--exclude", "tests/|venv/manage.py", "./"]  # mypy configuration file
      always_run: true
      files: ^.*\.py$
      pass_filenames: false
