version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-drf-app:latest
    environment:
      - SECRET_KEY=django-insecure-password
      - DJANGO_SETTINGS_MODULE=LibraryProject.settings
      - FORCE_NO_AUTH=false
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             /usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
