from __future__ import annotations

from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter  # type: ignore

from .views import CustomLoginView
from .views import CustomLogoutView
from .views import RegisterView
from .views import UserViewSet

app_name = "login_api"

router = DefaultRouter()
router.register(r"users", UserViewSet)


urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="api-login"),
    path("logout/", CustomLogoutView.as_view(), name="api-logout"),
    path("register/", RegisterView.as_view(), name="api-register"),
    path("", include(router.urls), name="users"),  # Attaching all paths generated by router
]
