from __future__ import annotations

from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter  # type: ignore
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView

from .views import RegisterView
from .views import UserViewSet

# from .views import CustomLoginView
# from .views import CustomLogoutView

app_name = "login_api"

router = DefaultRouter()
router.register(r"users", UserViewSet)


urlpatterns = [
    # path("login/", CustomLoginView.as_view(), name="api-login"),
    # path("logout/", CustomLogoutView.as_view(), name="api-logout"),
    path("token/", TokenObtainPairView.as_view(), name="api-token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="api-token_refresh"),
    path("register/", RegisterView.as_view(), name="api-register"),
    path("", include(router.urls), name="users"),  # Attaching all paths generated by router
]
