from __future__ import annotations

from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter  # type: ignore

from .views import AuthorBooksView
from .views import AuthorViewSet
from .views import BookCategoryViewSet
from .views import BookViewSet


router = DefaultRouter()
router.register(r"authors", AuthorViewSet)
router.register(r"books", BookViewSet)
router.register(r"categories", BookCategoryViewSet)


urlpatterns = [
    path("", include(router.urls)),  # Attaching all paths generated by router
    path("author/<int:pk>/books/", AuthorBooksView.as_view(), name="author-books"),
]
